import { StationId, SystemAlert } from '../types';

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alt-101',
    timestamp: '8 mins ago',
    stationId: 'maitri',
    severity: 'CRITICAL',
    title: 'Genset G2 Secondary Excitation Warning',
    description: 'Generator G2 field excitation current fluctuation detected (+8.4% above nominal). Automated safety limiter engaged.',
    rootCause: 'Low ambient intake temperature (-28°C) causing cold alternator brush contact impedance.',
    recommendedAction: 'Verify alternator pre-heater jacket circuit and prepare auxiliary Genset G3 for seamless transfer if instability persists.',
    acknowledged: false,
    dismissed: false,
    category: 'GENERATOR',
  },
  {
    id: 'alt-102',
    timestamp: '22 mins ago',
    stationId: 'maitri',
    severity: 'WARNING',
    title: 'Battery SOC Reserve Threshold Warning',
    description: 'Battery SOC expected to fall below 30% safety reserve threshold in 3 hours without generator dispatch adjustment.',
    rootCause: 'Prolonged calm period with wind speed decreasing from 18 m/s to 3.5 m/s.',
    recommendedAction: 'Engage Genset G1 at 80% optimal load point to supply station demand and float-charge BESS.',
    acknowledged: false,
    dismissed: false,
    category: 'BATTERY',
  },
  {
    id: 'alt-103',
    timestamp: '45 mins ago',
    stationId: 'maitri',
    severity: 'WARNING',
    title: 'High Thermal Heating Demand Predicted',
    description: 'Meteorological telemetry forecasts -8°C ambient temperature drop over next 4 hours. Estimated thermal load surge: +45 kW.',
    rootCause: 'Polar katabatic front descending from continental Antarctic ice sheet.',
    recommendedAction: 'Activate secondary hydronic heat exchanger and pre-warm life-support tracer loops.',
    acknowledged: true,
    dismissed: false,
    category: 'WEATHER',
  },
  {
    id: 'alt-104',
    timestamp: '1 hour ago',
    stationId: 'maitri',
    severity: 'INFO',
    title: 'Wind Turbine Fleet Generation Surge',
    description: 'Wind generation increased by 18% (82 kW peak), displacing 14.2 L/h of diesel consumption.',
    rootCause: 'Stable katabatic wind flow at 16.4 m/s within optimal turbine power curve.',
    recommendedAction: 'No action required. POLAR-EMS has automatically throttled generator output to minimum SFC envelope.',
    acknowledged: true,
    dismissed: false,
    category: 'RENEWABLE',
  },
  {
    id: 'alt-105',
    timestamp: '2 hours ago',
    stationId: 'maitri',
    severity: 'AI_INSIGHT',
    title: 'Midday Renewable Surplus Strategy',
    description: 'Renewable generation is expected to exceed current demand between 13:00–15:00. Recommended action: charge battery and run flexible water purification.',
    rootCause: 'Coincident high solar elevation (385 W/m²) and sustained coastal wind.',
    recommendedAction: 'Pre-schedule BESS high-current charging and cycle reverse-osmosis pump.',
    acknowledged: false,
    dismissed: false,
    category: 'LOAD',
  },
  {
    id: 'alt-201',
    timestamp: '15 mins ago',
    stationId: 'bharati',
    severity: 'INFO',
    title: 'Desalination Thermal Recovery Loop Active',
    description: 'CHP exhaust heat successfully harnessed for freshwater evaporator, saving 28 kW electrical heating.',
    rootCause: 'Optimal Genset G1 combined heat & power operational state.',
    recommendedAction: 'System running within peak thermal efficiency (91.5%).',
    acknowledged: true,
    dismissed: false,
    category: 'LOAD',
  },
  {
    id: 'alt-202',
    timestamp: '1 hour ago',
    stationId: 'bharati',
    severity: 'AI_INSIGHT',
    title: 'BESS Peak Shaving Opportunity Detected',
    description: 'Anticipated 55 kW laboratory instrument load surge at 16:00. Recommended strategy: deploy BESS rapid discharge to avoid starting Genset G2.',
    rootCause: 'Scheduled geological mass-spectrometry test run.',
    recommendedAction: 'Arm BESS automated peak-shaving algorithm at 15:55.',
    acknowledged: false,
    dismissed: false,
    category: 'BATTERY',
  },
];
