import { CriticalLoadItem, EnergyData, StationId } from '../types';

export const ENERGY_DATA: Record<StationId, EnergyData> = {
  maitri: {
    stationId: 'maitri',
    timestamp: new Date().toISOString(),
    currentLoadKW: 428,
    previousHourLoadKW: 408.4,
    loadTrendPercent: 4.8,
    
    solarGenerationKW: 72,
    windGenerationKW: 92,
    totalRenewableKW: 164,
    renewablePenetrationPercent: 38.3,
    
    batterySocPercent: 74,
    batteryCurrentKWh: 370,
    batteryCapacityKWh: 500,
    batteryFlowKW: 35, // Charging +35 kW
    batteryStatus: 'CHARGING',
    batteryHealthPercent: 96.8,
    
    fuelConsumptionRateLh: 32.6,
    dailyFuelConsumptionL: 782,
    baselineDailyFuelL: 895,
    fuelSavingsPercent: 12.6,
    fuelRemainingL: 142800, // Antarctic winter bulk storage
    fuelReserveDays: 182,
    
    criticalLoadKW: 182,
    criticalLoadProtectedPercent: 100,
    
    co2AvoidedDailyKg: 426,
    co2AvoidedTotalTonnes: 12.4,
  },
  bharati: {
    stationId: 'bharati',
    timestamp: new Date().toISOString(),
    currentLoadKW: 485,
    previousHourLoadKW: 472.0,
    loadTrendPercent: 2.7,
    
    solarGenerationKW: 112,
    windGenerationKW: 118,
    totalRenewableKW: 230,
    renewablePenetrationPercent: 47.4,
    
    batterySocPercent: 82,
    batteryCurrentKWh: 492,
    batteryCapacityKWh: 600,
    batteryFlowKW: 42,
    batteryStatus: 'CHARGING',
    batteryHealthPercent: 98.4,
    
    fuelConsumptionRateLh: 28.4,
    dailyFuelConsumptionL: 681,
    baselineDailyFuelL: 864,
    fuelSavingsPercent: 21.2,
    fuelRemainingL: 188500,
    fuelReserveDays: 276,
    
    criticalLoadKW: 210,
    criticalLoadProtectedPercent: 100,
    
    co2AvoidedDailyKg: 598,
    co2AvoidedTotalTonnes: 18.2,
  },
};

export const CRITICAL_LOADS: Record<StationId, CriticalLoadItem[]> = {
  maitri: [
    {
      id: 'load-heat',
      name: 'Habitat & Line Thermal Tracing',
      category: 'CRITICAL',
      powerKW: 142,
      percentage: 33.2,
      status: 'PROTECTED',
      subsystem: 'Thermal & Life Support',
      minTempRequirementC: 18,
    },
    {
      id: 'load-med',
      name: 'Medical Ward & Oxygen Plant',
      category: 'CRITICAL',
      powerKW: 22,
      percentage: 5.1,
      status: 'PROTECTED',
      subsystem: 'Emergency Life Support',
    },
    {
      id: 'load-comm',
      name: 'Satellite SATCOM & VHF Mesh',
      category: 'CRITICAL',
      powerKW: 18,
      percentage: 4.2,
      status: 'PROTECTED',
      subsystem: 'National Comms Link',
    },
    {
      id: 'load-water',
      name: 'Priyadarshini Lake Water Pump',
      category: 'IMPORTANT',
      powerKW: 64,
      percentage: 15.0,
      status: 'PROTECTED',
      subsystem: 'Hydrology & Supply',
    },
    {
      id: 'load-lab',
      name: 'Atmospheric Physics & Seismo Lab',
      category: 'IMPORTANT',
      powerKW: 88,
      percentage: 20.5,
      status: 'OPTIMIZED',
      subsystem: 'Scientific Instruments',
    },
    {
      id: 'load-cold',
      name: 'Sample Cryo & Provisions Storage',
      category: 'FLEXIBLE',
      powerKW: 94,
      percentage: 22.0,
      status: 'OPTIMIZED',
      subsystem: 'Auxiliary Facilities',
    },
  ],
  bharati: [
    {
      id: 'load-heat-b',
      name: 'Main Station HVAC & Hydronic Loop',
      category: 'CRITICAL',
      powerKW: 165,
      percentage: 34.0,
      status: 'PROTECTED',
      subsystem: 'HVAC Life Support',
    },
    {
      id: 'load-med-b',
      name: 'ICU Unit & Emergency Surgical Bay',
      category: 'CRITICAL',
      powerKW: 25,
      percentage: 5.2,
      status: 'PROTECTED',
      subsystem: 'Medical Life Support',
    },
    {
      id: 'load-comm-b',
      name: 'ISRO Telemetry Tracking & Comm',
      category: 'CRITICAL',
      powerKW: 20,
      percentage: 4.1,
      status: 'PROTECTED',
      subsystem: 'Space & Comms Array',
    },
    {
      id: 'load-water-b',
      name: 'Seawater Desalination Plant',
      category: 'IMPORTANT',
      powerKW: 75,
      percentage: 15.5,
      status: 'PROTECTED',
      subsystem: 'Potable Water System',
    },
    {
      id: 'load-lab-b',
      name: 'Oceanography & Geomagnetic Lab',
      category: 'IMPORTANT',
      powerKW: 105,
      percentage: 21.6,
      status: 'OPTIMIZED',
      subsystem: 'Research Modules',
    },
    {
      id: 'load-cold-b',
      name: 'Deep Core Ice Storage Vaults',
      category: 'FLEXIBLE',
      powerKW: 95,
      percentage: 19.6,
      status: 'OPTIMIZED',
      subsystem: 'Sample Preservation',
    },
  ],
};
