import { Generator, StationId } from '../types';

export const GENERATORS: Record<StationId, Generator[]> = {
  maitri: [
    {
      id: 'G1',
      name: 'Primary Genset G1 (Kirloskar 125kVA)',
      model: 'Kirloskar Arctic Heavy-Duty 125kVA Diesel',
      status: 'RUNNING',
      outputKW: 128,
      maxOutputKW: 160,
      efficiencyPercent: 88.4,
      fuelConsumptionLh: 18.2,
      runtimeHours: 3420,
      loadPercentage: 80,
      temperatureC: 82.5,
      oilPressureBar: 4.8,
      frequencyHz: 50.02,
      voltageV: 415.2,
    },
    {
      id: 'G2',
      name: 'Secondary Genset G2 (Kirloskar 125kVA)',
      model: 'Kirloskar Arctic Heavy-Duty 125kVA Diesel',
      status: 'RUNNING',
      outputKW: 101,
      maxOutputKW: 160,
      efficiencyPercent: 86.2,
      fuelConsumptionLh: 14.4,
      runtimeHours: 2890,
      loadPercentage: 63,
      temperatureC: 78.1,
      oilPressureBar: 4.6,
      frequencyHz: 49.98,
      voltageV: 414.8,
    },
    {
      id: 'G3',
      name: 'Auxiliary Genset G3 (Kirloskar 125kVA)',
      model: 'Kirloskar Arctic Heavy-Duty 125kVA Diesel',
      status: 'STANDBY',
      outputKW: 0,
      maxOutputKW: 160,
      efficiencyPercent: 0,
      fuelConsumptionLh: 0,
      runtimeHours: 1940,
      loadPercentage: 0,
      temperatureC: 45.0, // Pre-heated block jacket
      oilPressureBar: 0,
      frequencyHz: 0,
      voltageV: 0,
    },
    {
      id: 'G4',
      name: 'Emergency Life Support Genset G4',
      model: 'Cummins Emergency Cold-Start 80kVA',
      status: 'STANDBY',
      outputKW: 0,
      maxOutputKW: 100,
      efficiencyPercent: 0,
      fuelConsumptionLh: 0,
      runtimeHours: 412,
      loadPercentage: 0,
      temperatureC: 42.0,
      oilPressureBar: 0,
      frequencyHz: 0,
      voltageV: 0,
    },
  ],
  bharati: [
    {
      id: 'G1',
      name: 'CHP Genset G1 (Volvo Penta 200kVA)',
      model: 'Volvo Penta D13 Marine/Arctic CHP',
      status: 'RUNNING',
      outputKW: 145,
      maxOutputKW: 180,
      efficiencyPercent: 91.5,
      fuelConsumptionLh: 17.5,
      runtimeHours: 4180,
      loadPercentage: 81,
      temperatureC: 84.0,
      oilPressureBar: 5.1,
      frequencyHz: 50.01,
      voltageV: 415.0,
    },
    {
      id: 'G2',
      name: 'CHP Genset G2 (Volvo Penta 200kVA)',
      model: 'Volvo Penta D13 Marine/Arctic CHP',
      status: 'RUNNING',
      outputKW: 110,
      maxOutputKW: 180,
      efficiencyPercent: 88.0,
      fuelConsumptionLh: 13.8,
      runtimeHours: 3750,
      loadPercentage: 61,
      temperatureC: 80.2,
      oilPressureBar: 4.9,
      frequencyHz: 50.0,
      voltageV: 415.1,
    },
    {
      id: 'G3',
      name: 'CHP Genset G3 (Volvo Penta 200kVA)',
      model: 'Volvo Penta D13 Marine/Arctic CHP',
      status: 'STANDBY',
      outputKW: 0,
      maxOutputKW: 180,
      efficiencyPercent: 0,
      fuelConsumptionLh: 0,
      runtimeHours: 2150,
      loadPercentage: 0,
      temperatureC: 48.0,
      oilPressureBar: 0,
      frequencyHz: 0,
      voltageV: 0,
    },
    {
      id: 'G4',
      name: 'Harbour / Survival Genset G4',
      model: 'Caterpillar 100kVA Survival Unit',
      status: 'STANDBY',
      outputKW: 0,
      maxOutputKW: 120,
      efficiencyPercent: 0,
      fuelConsumptionLh: 0,
      runtimeHours: 630,
      loadPercentage: 0,
      temperatureC: 45.0,
      oilPressureBar: 0,
      frequencyHz: 0,
      voltageV: 0,
    },
  ],
};
