/**
 * POLAR-EMS Scientific Provenance Aggregator & Classifier
 * 
 * Tracks, normalizes, and generates transparent provenance metadata across
 * RAG knowledge chunks, real sensor telemetry, modeled datasets, forecasts,
 * optimization outputs, and simulation runs.
 */

const { PROVENANCE_TYPES } = require('./schemas');

class ProvenanceService {
  /**
   * Normalizes an individual raw provenance string or array into standard tags.
   */
  normalizeProvenance(raw) {
    if (!raw) return [PROVENANCE_TYPES.UNAVAILABLE];

    const list = Array.isArray(raw) ? raw : [raw];
    const normalized = new Set();

    for (const item of list) {
      if (!item || typeof item !== 'string') continue;
      const clean = item.trim().toUpperCase();

      if (clean.includes('REAL / MEASURED') || clean === 'REAL' || clean === 'MEASURED') {
        normalized.add(PROVENANCE_TYPES.REAL_MEASURED);
      } else if (clean.includes('REAL CLIMATOLOGY') || clean.includes('CLIMATOLOGY')) {
        normalized.add(PROVENANCE_TYPES.REAL_CLIMATOLOGY);
      } else if (clean.includes('MODELED') || clean.includes('SCENARIO') || clean.includes('SYNTHETIC')) {
        normalized.add(PROVENANCE_TYPES.MODELED_SCENARIO);
      } else if (clean.includes('ENGINEERING ASSUMPTION') || clean.includes('ASSUMPTION') || clean.includes('SPECIFICATION')) {
        normalized.add(PROVENANCE_TYPES.ENGINEERING_ASSUMPTION);
      } else if (clean.includes('OPTIMIZATION') || clean.includes('DISPATCH') || clean.includes('SOLVER')) {
        normalized.add(PROVENANCE_TYPES.OPTIMIZATION);
      } else if (clean.includes('UNAVAILABLE') || clean.includes('UNKNOWN')) {
        normalized.add(PROVENANCE_TYPES.UNAVAILABLE);
      } else {
        normalized.add(item.trim());
      }
    }

    return normalized.size > 0 ? Array.from(normalized) : [PROVENANCE_TYPES.UNAVAILABLE];
  }

  /**
   * Extracts and consolidates all distinct provenance tags from a collection of evidence objects.
   */
  extractProvenanceFromEvidence(evidenceList = []) {
    const allTags = new Set();

    for (const ev of evidenceList) {
      if (ev.provenance) {
        const tags = this.normalizeProvenance(ev.provenance);
        tags.forEach((t) => allTags.add(t));
      }
    }

    if (allTags.size === 0) {
      allTags.add(PROVENANCE_TYPES.ENGINEERING_ASSUMPTION);
    }

    return Array.from(allTags);
  }

  /**
   * Generates a scientific, judge-ready disclaimer summary if mixed or modeled data was used.
   */
  generateProvenanceSummary(provenanceList = []) {
    const notes = [];

    if (provenanceList.includes(PROVENANCE_TYPES.REAL_MEASURED)) {
      notes.push('Weather data represents physical in-situ automated weather station (AWS) measurements from Maitri Station (2019).');
    }
    if (provenanceList.includes(PROVENANCE_TYPES.REAL_CLIMATOLOGY)) {
      notes.push('Solar radiation baselines derive from India Meteorological Department (IMD) 1985–2000 polar solar archives.');
    }
    if (provenanceList.includes(PROVENANCE_TYPES.MODELED_SCENARIO)) {
      notes.push('Solar PV generation, wind power, and electrical load profiles are deterministic scenario models conforming to IEC 61724-1 standards.');
    }
    if (provenanceList.includes(PROVENANCE_TYPES.OPTIMIZATION)) {
      notes.push('Dispatch schedules and generator commitments represent mathematical solutions generated by Google OR-Tools MILP optimizer.');
    }
    if (provenanceList.includes(PROVENANCE_TYPES.ENGINEERING_ASSUMPTION)) {
      notes.push('System characteristics and life-support circuit priorities derive from polar habitat engineering specifications.');
    }

    return notes;
  }
}

module.exports = new ProvenanceService();
